// DEV-ONLY: sample fixture for the #/__preview harness.
// Populated with realistic data so every UI surface looks alive.
// All ids are stable strings (not random) so the preview renders consistently.

import type { DeanDBData } from "../../types";

export const sampleJourney: DeanDBData = {
  listener: {
    meterName: "Dean",
    tagline:
      "250 hours of discography deep-dives — rating every album from front to back, one artist at a time.",
  },
  goalHours: 250,
  season: "Season 3 · Summer of Soul",
  artists: [
    // ── 1. Frank Ocean — marathon, partially done, 1 album rated 10 ──────────
    {
      id: "artist-frank-ocean",
      name: "Frank Ocean",
      genre: "R&B / Soul",
      country: "USA",
      bio: "One of the most singular voices in contemporary R&B, Frank Ocean redefined what a pop album could sound like in the 2010s. His meticulous craftsmanship and confessional lyricism make every release an event.",
      color: ["#3b82f6", "#1e3a8a"],
      catalogSize: 3,
      logged: false,
      verdict: 9.4,
      verdictNote:
        "Possibly the most important artist of the decade. Blonde alone cements his legacy.",

      albums: [
        {
          id: "album-blonde",
          title: "Blonde",
          year: 2016,
          cover: ["#3b82f6", "#1e3a8a"],
          coverUrl: undefined,
          status: "completed",
          rating: 10,
          review:
            "A masterpiece of modern R&B that refuses easy categorisation. Blonde is simultaneously intimate and vast — each listen reveals new textures, new emotional registers. The production is alien and warm at once. 'Godspeed', 'Self Control', 'Nights' — these are songs I'll carry for the rest of my life. An easy 10. I cannot think of a single thing I would change about this album. Every track earns its place.",
          minutes: 60,
          dateListened: "2024-06-15",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-nikes", title: "Nikes", rating: 9, favorite: false },
            { id: "trk-ivy", title: "Ivy", rating: 10, favorite: true },
            { id: "trk-pink-matter", title: "Pink + White", rating: 9, favorite: false },
            { id: "trk-self-control", title: "Self Control", rating: 10, favorite: true },
            { id: "trk-godspeed", title: "Godspeed", rating: 10, favorite: true },
          ],
        },
        {
          id: "album-channel-orange",
          title: "Channel Orange",
          year: 2012,
          cover: ["#f59e0b", "#92400e"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.1,
          review:
            "A stunning debut full-length that arrived almost fully-formed. The storytelling on 'Pyramids' alone is worth the price of admission.",
          minutes: 68,
          dateListened: "2024-05-02",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-thinkin-bout-you", title: "Thinkin Bout You", rating: 9, favorite: false },
            { id: "trk-super-rich-kids", title: "Super Rich Kids", rating: 8, favorite: false },
            { id: "trk-pyramids", title: "Pyramids", rating: 10, favorite: true },
            { id: "trk-lost", title: "Lost", rating: 9, favorite: true },
            { id: "trk-bad-religion", title: "Bad Religion", rating: 9, favorite: false },
          ],
        },
        {
          id: "album-nostalgia-ultra",
          title: "Nostalgia, Ultra",
          year: 2011,
          cover: ["#14b8a6", "#134e4a"],
          coverUrl: undefined,
          status: "listening",
          rating: null,
          review: "",
          minutes: 48,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [
            { id: "trk-nature-feels", title: "Nature Feels", rating: null, favorite: false },
            { id: "trk-novacane", title: "Novacane", rating: 8, favorite: true },
            { id: "trk-lovecrimes", title: "Lovecrimes", rating: null, favorite: false },
          ],
        },
      ],
    },

    // ── 2. Radiohead — marathon, nearly complete ──────────────────────────────
    {
      id: "artist-radiohead",
      name: "Radiohead",
      genre: "Art Rock / Electronic",
      country: "UK",
      bio: "Radiohead spent three decades systematically dismantling everything rock music thought it was. From the anthemic angst of 'The Bends' to the fractured electronica of 'Kid A', they've never made the same record twice.",
      color: ["#ef4444", "#7c2d12"],
      catalogSize: 9,
      logged: false,
      verdict: 9.0,
      verdictNote: "The most consistently excellent band of the last thirty years. No filler era.",

      albums: [
        {
          id: "album-in-rainbows",
          title: "In Rainbows",
          year: 2007,
          cover: ["#ef4444", "#7c2d12"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.8,
          review:
            "If you had to pick one Radiohead album for someone who'd never heard them, it would be this one. Warm, human, and devastatingly beautiful. '15 Step' into 'Bodysnatchers' might be the greatest one-two opening in their catalogue.",
          minutes: 42,
          dateListened: "2024-04-10",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-15step", title: "15 Step", rating: 9, favorite: false },
            { id: "trk-bodysnatchers", title: "Bodysnatchers", rating: 10, favorite: true },
            { id: "trk-nude", title: "Nude", rating: 10, favorite: true },
            { id: "trk-weird-fishes", title: "Weird Fishes/Arpeggi", rating: 10, favorite: true },
            { id: "trk-reckoner", title: "Reckoner", rating: 9, favorite: false },
          ],
        },
        {
          id: "album-kid-a",
          title: "Kid A",
          year: 2000,
          cover: ["#a855f7", "#4c1d95"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.5,
          review:
            "The sound of a band throwing everything they knew into the ocean and starting again. 'Everything in Its Right Place' is one of the most unsettling and transcendent album openers ever recorded.",
          minutes: 50,
          dateListened: "2024-03-25",
          favorite: false,
          excluded: false,
          tracks: [
            { id: "trk-eirp", title: "Everything in Its Right Place", rating: 10, favorite: true },
            { id: "trk-kid-a", title: "Kid A", rating: 9, favorite: false },
            { id: "trk-national-anthem", title: "The National Anthem", rating: 9, favorite: false },
            { id: "trk-how-to-disappear", title: "How to Disappear Completely", rating: 10, favorite: true },
            { id: "trk-idioteque", title: "Idioteque", rating: 10, favorite: true },
          ],
        },
        {
          id: "album-ok-computer",
          title: "OK Computer",
          year: 1997,
          cover: ["#10b981", "#064e3b"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.6,
          review:
            "The defining rock album of its era. 'No Surprises', 'Karma Police', 'Exit Music' — this record predicted the paranoia of the internet age before it fully arrived.",
          minutes: 53,
          dateListened: "2024-02-14",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-airbag", title: "Airbag", rating: 9, favorite: false },
            { id: "trk-paranoid-android", title: "Paranoid Android", rating: 10, favorite: true },
            { id: "trk-subterranean", title: "Subterranean Homesick Alien", rating: 8, favorite: false },
            { id: "trk-no-surprises", title: "No Surprises", rating: 10, favorite: true },
            { id: "trk-karma-police", title: "Karma Police", rating: 9, favorite: false },
          ],
        },
        {
          id: "album-the-bends",
          title: "The Bends",
          year: 1995,
          cover: ["#f97316", "#7c2d12"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 48,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
      ],
    },

    // ── 3. Joni Mitchell — marathon, completed (logged Library artist) ─────────
    {
      id: "artist-joni-mitchell",
      name: "Joni Mitchell",
      genre: "Folk / Singer-Songwriter",
      country: "Canada",
      bio: "One of the greatest songwriters who ever lived. Her open-tuning guitar innovations and literary lyricism set a standard that has never been surpassed. Blue is frequently cited as the greatest album ever recorded.",
      color: ["#ec4899", "#831843"],
      catalogSize: 19,
      logged: true,
      verdict: 9.7,
      verdictNote: "Blue is a perfect record. Nothing else sounds quite like it.",

      albums: [
        {
          id: "album-blue",
          title: "Blue",
          year: 1971,
          cover: ["#ec4899", "#831843"],
          coverUrl: undefined,
          status: "completed",
          rating: 10,
          review:
            "The most nakedly honest record I've ever heard. Every track feels like a window into a real human being. 'River' is the most devastating song ever written about loneliness. An absolute, unconditional 10.",
          minutes: 35,
          dateListened: "2023-12-01",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-all-i-want", title: "All I Want", rating: 10, favorite: true },
            { id: "trk-my-old-man", title: "My Old Man", rating: 9, favorite: false },
            { id: "trk-little-green", title: "Little Green", rating: 10, favorite: true },
            { id: "trk-carey", title: "Carey", rating: 9, favorite: false },
            { id: "trk-river", title: "River", rating: 10, favorite: true },
          ],
        },
        {
          id: "album-court-and-spark",
          title: "Court and Spark",
          year: 1974,
          cover: ["#a855f7", "#4c1d95"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.2,
          review:
            "Her commercial peak and arguably her most accessible record without being any less brilliant. 'Help Me' is one of the great pop songs.",
          minutes: 40,
          dateListened: "2024-01-10",
          favorite: false,
          excluded: false,
          tracks: [
            { id: "trk-court-and-spark", title: "Court and Spark", rating: 9, favorite: false },
            { id: "trk-help-me", title: "Help Me", rating: 10, favorite: true },
            { id: "trk-free-man", title: "Free Man in Paris", rating: 9, favorite: false },
            { id: "trk-people-parties", title: "People's Parties", rating: 8, favorite: false },
          ],
        },
      ],
    },

    // ── 4. Stevie Wonder — marathon, several completed ────────────────────────
    {
      id: "artist-stevie-wonder",
      name: "Stevie Wonder",
      genre: "Soul / Funk / R&B",
      country: "USA",
      bio: "Stevie Wonder's so-called 'classic period' between 1972 and 1976 is one of the most staggering runs in recorded music history. A savant who mastered every instrument and synthesiser within reach.",
      color: ["#f59e0b", "#92400e"],
      catalogSize: 23,
      logged: false,
      verdict: 9.3,
      verdictNote:
        "Innervisions alone earns this score. The classic period is untouchable.",

      albums: [
        {
          id: "album-innervisions",
          title: "Innervisions",
          year: 1973,
          cover: ["#f59e0b", "#92400e"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.7,
          review:
            "One of the most perfectly sequenced albums in existence. 'Living for the City' is a five-minute movie. 'Higher Ground' is the greatest funk record ever made. The fact that Stevie wrote, played and produced this in a burst of creativity is almost insane.",
          minutes: 44,
          dateListened: "2024-07-01",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-too-high", title: "Too High", rating: 9, favorite: false },
            { id: "trk-visions", title: "Visions", rating: 9, favorite: false },
            { id: "trk-living-city", title: "Living for the City", rating: 10, favorite: true },
            { id: "trk-higher-ground", title: "Higher Ground", rating: 10, favorite: true },
            { id: "trk-dont-you-worry", title: "Don't You Worry 'Bout a Thing", rating: 9, favorite: false },
          ],
        },
        {
          id: "album-songs-in-the-key",
          title: "Songs in the Key of Life",
          year: 1976,
          cover: ["#10b981", "#064e3b"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.4,
          review:
            "An audacious double album that somehow never overstays its welcome. 'As', 'Sir Duke', 'Isn't She Lovely' — hit after hit after hit. Nothing has captured this much joy on tape before or since.",
          minutes: 105,
          dateListened: "2024-07-20",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-love-having-you", title: "Love's in Need of Love Today", rating: 9, favorite: false },
            { id: "trk-have-a-talk", title: "Have a Talk with God", rating: 8, favorite: false },
            { id: "trk-village-ghetto", title: "Village Ghetto Land", rating: 9, favorite: false },
            { id: "trk-contusion", title: "Contusion", rating: 8, favorite: false },
            { id: "trk-sir-duke", title: "Sir Duke", rating: 10, favorite: true },
            { id: "trk-isnt-she-lovely", title: "Isn't She Lovely", rating: 10, favorite: true },
          ],
        },
        {
          id: "album-talking-book",
          title: "Talking Book",
          year: 1972,
          cover: ["#3b82f6", "#1e3a8a"],
          coverUrl: undefined,
          status: "completed",
          rating: 8.9,
          review:
            "The record where Stevie first truly became Stevie. Superstition is one of the great opening statements of any album, full stop.",
          minutes: 42,
          dateListened: "2024-06-30",
          favorite: false,
          excluded: false,
          tracks: [
            { id: "trk-you-are-sunshine", title: "You Are the Sunshine of My Life", rating: 9, favorite: false },
            { id: "trk-superstition", title: "Superstition", rating: 10, favorite: true },
            { id: "trk-big-brother", title: "Big Brother", rating: 8, favorite: false },
          ],
        },
        {
          id: "album-fulfillingness",
          title: "Fulfillingness' First Finale",
          year: 1974,
          cover: ["#a855f7", "#4c1d95"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
      ],
    },

    // ── 5. D'Angelo — marathon, partially done ────────────────────────────────
    {
      id: "artist-dangelo",
      name: "D'Angelo",
      genre: "Neo-Soul / Funk",
      country: "USA",
      bio: "The architect of neo-soul who then disappeared for fourteen years before returning with one of the greatest comebacks in music history. Voodoo is a masterclass in groove and restraint.",
      color: ["#a855f7", "#4c1d95"],
      catalogSize: 3,
      logged: false,
      verdict: null,
      verdictNote: "",

      albums: [
        {
          id: "album-voodoo",
          title: "Voodoo",
          year: 2000,
          cover: ["#a855f7", "#4c1d95"],
          coverUrl: undefined,
          status: "completed",
          rating: 9.3,
          review:
            "The greatest groove record of the post-Prince era. Every track breathes, every drum lands slightly behind the beat on purpose. 'Spanish Joint' is intoxicating. The way this album feels is more important than what it says — and that is entirely the point.",
          minutes: 71,
          dateListened: "2024-08-05",
          favorite: true,
          excluded: false,
          tracks: [
            { id: "trk-playa-playa", title: "Playa Playa", rating: 8, favorite: false },
            { id: "trk-devil-pie", title: "Devil's Pie", rating: 9, favorite: false },
            { id: "trk-left-right", title: "Left & Right", rating: 9, favorite: true },
            { id: "trk-spanish-joint", title: "Spanish Joint", rating: 10, favorite: true },
            { id: "trk-africa", title: "Africa", rating: 9, favorite: false },
          ],
        },
        {
          id: "album-black-messiah",
          title: "Black Messiah",
          year: 2014,
          cover: ["#ec4899", "#831843"],
          coverUrl: undefined,
          status: "listening",
          rating: null,
          review: "",
          minutes: 52,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [
            { id: "trk-ain-that-easy", title: "Ain't That Easy", rating: null, favorite: false },
            { id: "trk-1000-deaths", title: "1000 Deaths", rating: 8, favorite: false },
            { id: "trk-really-love", title: "Really Love", rating: 9, favorite: true },
          ],
        },
        {
          id: "album-brown-sugar",
          title: "Brown Sugar",
          year: 1995,
          cover: ["#f97316", "#7c2d12"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
      ],
    },

    // ── 6. Sade — FULLY UNSTARTED marathon artist (Wheel eligible) ────────────
    {
      id: "artist-sade",
      name: "Sade",
      genre: "Quiet Storm / Soul",
      country: "UK / Nigeria",
      bio: "Sade Adu's velvet voice and the band's signature understated production created a sound that no one has successfully replicated. Every album is essentially the same idea executed with slightly different production — and somehow it never gets old.",
      color: ["#14b8a6", "#134e4a"],
      catalogSize: 6,
      logged: false,
      verdict: null,
      verdictNote: "",

      albums: [
        {
          id: "album-diamond-life",
          title: "Diamond Life",
          year: 1984,
          cover: ["#14b8a6", "#134e4a"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
        {
          id: "album-stronger-than-pride",
          title: "Stronger Than Pride",
          year: 1988,
          cover: ["#10b981", "#064e3b"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
        {
          id: "album-love-deluxe",
          title: "Love Deluxe",
          year: 1992,
          cover: ["#3b82f6", "#1e3a8a"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
      ],
    },

    // ── 7. Massive Attack — FULLY UNSTARTED marathon artist (Wheel eligible) ──
    {
      id: "artist-massive-attack",
      name: "Massive Attack",
      genre: "Trip-Hop / Electronic",
      country: "UK",
      bio: "The inventors of trip-hop, Massive Attack built a catalogue of brooding, cinematic records that essentially created an entire subgenre. Mezzanine remains one of the most atmospheric albums ever recorded.",
      color: ["#ef4444", "#7c2d12"],
      catalogSize: 5,
      logged: false,
      verdict: null,
      verdictNote: "",

      albums: [
        {
          id: "album-blue-lines",
          title: "Blue Lines",
          year: 1991,
          cover: ["#ef4444", "#7c2d12"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
        {
          id: "album-mezzanine",
          title: "Mezzanine",
          year: 1998,
          cover: ["#a855f7", "#4c1d95"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
        {
          id: "album-protection",
          title: "Protection",
          year: 1994,
          cover: ["#f97316", "#7c2d12"],
          coverUrl: undefined,
          status: "want",
          rating: null,
          review: "",
          minutes: 0,
          dateListened: null,
          favorite: false,
          excluded: false,
          tracks: [],
        },
      ],
    },
  ],
};
